name: Build Windows Samera
on: [workflow_dispatch]
jobs:
  windows:
    runs-on: windows-2022
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: microsoft/setup-msbuild@v2
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
        vcpkgTriplet: x86-windows-static
        vcpkgGitCommitId: 9edb1b8e590cc086563301d735cae4b6e732d2d2
        vcpkgArguments: >
          boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem
          luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl
    - name: Integrate vcpkg
      run: ${{ runner.workspace }}/vcpkg/vcpkg integrate install
    - name: Compile otclient_gl
      run: |
        cd vc16
        MSBuild /property:Configuration=OpenGL /p:BUILD_REVISION=${{ github.run_number }}
    - uses: actions/upload-artifact@v4
      with:
        name: Download-binaries
        path: otclient_gl.exe
        if-no-files-found: error
